<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows10.0.19041.0</TargetFramework><UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>disable</ImplicitUsings><PlatformTarget>x64</PlatformTarget><AssemblyName>KotobaSUB</AssemblyName></PropertyGroup>
  <ItemGroup><ProjectReference Include="../KotobaSUB.Core/KotobaSUB.Core.csproj" /></ItemGroup>
</Project>
