<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../KotobaSUB.Core/KotobaSUB.Core.csproj" />
    <PackageReference Include="LibNMeCab" Version="0.10.2" />
    <PackageReference Include="LibNMeCab.IpaDicBin" Version="0.10.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>
</Project>
